#!/usr/bin/env bash
# performing a 301 that is moved permanently

# package update before installation
sudo apt-get update
sudo apt-get install -y nginx

# creating index.html page
echo "Hello World!" | sudo tee /var/www/html/index.html

# 301 redirections
string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/besthor permanent;"
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# restarting the nginx
sudo servive nginx restart

