#!/usr/bin/env bash
# performing a customization of the 404 error page

# package update before installation
sudo apt-get update
sudo apt-get install -y nginx

# creating index.html page
echo "Hello World!" | sudo tee /var/www/html/index.html

# 301 redirections
string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/besthor permanent;"
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

#createinga 404 errorpage
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

string_for_replace="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"

sudo sed -i "s/listen 80 default_server;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# restarting the nginx
sudo servive nginx restart

