#!/usr/bin/env bash
# installling load ballancer

sudo apt-get -y update
sudo apt-get -y install haproxy
sudo chown $USER:USER /etc/haproxy/haproxy.cfg

echo "
frontend eugenedevops
    bind *:80
    mode http
    default_backend app

backend app
    ballance roundrobin
    server 109527-web-01 54.88.121.94:80 check
    server 109527-web-02 35.153.67.206:80 check" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
