#!/usr/bin/env bash
# creating a script to configure install and configure HAProxy on on lb-01 server

sudo apt-get update
sudo apt-get install -y haproxy

# edited configuration file
server_config=\
"
frontend  besthor_frontend
        bind *:80
        mode http
        default_backend besthor_backend
backend besthor_backend
        balance roundrobin
        server 109527-web-01 54.208.50.219:80 check
        server 109527-web-02 52.3.248.94:80:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# Testing the HAproxy configuration file
sudo haproxy -c -f /etc/haproxy/haproxy.cfg

# Restart the Nginx service
sudo service haproxy restart
