#!/usr/bin/env bash
# configures the nginx server to listen to port 80

cat /etc/nginx/sites-available/default >  /etc/nginx/sites-enabled/default

# Reatsrting the nginx server
service nginx restart


