#!/usr/bin/env bash
#A bash scipt to:
# create a file/var/run/myscript.pid with its pid
# Displays "To infinity and beyond" indefinitely
# Displays "I hate the kill command" upon receiving a SIGTERM
# Displays "Y U no love me?!" on SIGQUIT or sigterm Signal.
# Deletes the pid file and terminates on SIGQUIT or SIGTERM signal.
trap "echo i hate the kill command; exit" SIGTERM
trap "echo Y U no love me?!" SIGINT
trap "exit" SiGqUIT

echo $$ > /var/run/myscript.pid

while true
do
	echo "To infinity and beyond"
	sleep 10
done
