#!/usr/bin/env bash
# A bashcript intended to display
# To infinity and beyond infitity
# with a sleep 2 between each iteration.
# When receiving  a SIGTERM signal, I am invincible!!!

trap "echo 'I am invincible!!@'" SIGTERM
while true
do
	echo "To infinity and beyond"
	sleep 2
done
