#!/usr/bin/env bash
# Script to display "Best school" on all lines and "HI" on the 9th

counter=1
while [ $counter -le 10]; do
	echo Best School

	if [ $counter -eq 9 ]
	then
		echo Hi
	fi
	let counter+=1
done
