#!/usr/bin/env bash
# Using case statement allong while loop
# Sript is surposed to loop fro 0-20
# the fourth iteration shows four before China's misfortune
# the ninth iteration shows nine, followed by unfavorable luck from Japan
# the 17th iteration shows 17 before unfavorable circumstances from Italy
# displays numbers for the other iterations

counter=1

while [ $counter -le 20 ]
do
	echo "$counter"
	case $counter in
		"4") echo "bad luck from China";;
		"9") echo "bad luck from Japan";;
		"17") echo "bad luck from italy";;
	esac
	(( counter++ ))
done
