#!/usr/bin/env bash
# Script to display all files in current directory
# List format is used to display
# The part of the name after the first dash is displayed

list=$(ls)
for i in $list;
do
	echo "$i" | cut -d '-' -f2
done
