#!/usr/bin/env bash
# installing the ufw firewalls and setup afew configurations to the firewall

sudo apt install -y ufw
sudo ufw default allow outgoing
sudo ufw default deny incoming
sudo ufw allow 22
sudo ufw allow 443
sudo ufw allow 80
sudo ufw enable
